export const OPEN_CLOSE = 'OPEN_CLOSE'
export const SET_CLS_MENU = 'SET_CLS_MENU'
export const SET_ACTIVE_CLS_MENU = 'SET_ACTIVE_CLS_MENU'
export const INPUT_NAME_ACTIVE = 'INPUT_NAME_ACTIVE'
export const INPUT_PHONE_ACTIVE = 'INPUT_PHONE_ACTIVE'
export const INPUT_EMAIL_ACTIVE = 'INPUT_EMAIL_ACTIVE'
export const INPUT_NAME_PASSIVE = 'INPUT_NAME_PASSIVE'
export const INPUT_PHONE_PASSIVE = 'INPUT_PHONE_PASSIVE'
export const INPUT_EMAIL_PASSIVE = 'INPUT_EMAIL_PASSIVE'


